// Layer 3: Monitoring - Windows VM Monitoring (AMA + DCR)
// Dependencies: vm (vmResourceId), log_analytics (workspaceResourceId)

param location string
param tags object = {}
param namePrefix string
param vmResourceId string
param workspaceResourceId string

var vmName = last(split(vmResourceId, '/'))
var dcrName = '${namePrefix}-windows-dcr'

resource vm 'Microsoft.Compute/virtualMachines@2024-07-01' existing = {
  name: vmName
}

resource amaExtension 'Microsoft.Compute/virtualMachines/extensions@2023-09-01' = {
  parent: vm
  name: 'AzureMonitorWindowsAgent'
  location: location
  properties: {
    publisher: 'Microsoft.Azure.Monitor'
    type: 'AzureMonitorWindowsAgent'
    typeHandlerVersion: '1.22'
    autoUpgradeMinorVersion: true
    enableAutomaticUpgrade: true
  }
}

// Mirrors the known-good DCR generated by the Azure portal. All Windows event
// channels share one Microsoft-Event data source, including Sysmon.
resource dcr 'Microsoft.Insights/dataCollectionRules@2023-03-11' = {
  name: dcrName
  location: location
  tags: tags
  properties: {
    dataSources: {
      performanceCounters: [
        {
          streams: [
            'Microsoft-Perf'
          ]
          samplingFrequencyInSeconds: 60
          counterSpecifiers: [
            '\\Processor(_Total)\\% Processor Time'
            '\\Memory\\Available Bytes'
            '\\Memory\\% Committed Bytes In Use'
            '\\LogicalDisk(_Total)\\Disk Reads/sec'
            '\\LogicalDisk(_Total)\\Disk Writes/sec'
            '\\LogicalDisk(_Total)\\% Free Space'
            '\\Network Interface(*)\\Bytes Total/sec'
            '\\Process(_Total)\\Handle Count'
            '\\Process(_Total)\\Thread Count'
            '\\System\\Processor Queue Length'
          ]
          name: 'PerformanceCountersDataSource'
        }
      ]
      windowsEventLogs: [
        {
          streams: [
            'Microsoft-Event'
          ]
          xPathQueries: [
            'Security!*'
            'Microsoft-Windows-PowerShell/Operational!*'
            'Microsoft-Windows-Windows Defender/Operational!*'
            'System!*[System[(Level=1 or Level=2)]]'
            'Microsoft-Windows-Sysmon/Operational!*'
          ]
          name: 'WindowsEventLogsDataSource'
        }
      ]
    }
    destinations: {
      logAnalytics: [
        {
          workspaceResourceId: workspaceResourceId
          name: 'la-workspace'
        }
      ]
    }
    dataFlows: [
      {
        streams: [
          'Microsoft-Event'
        ]
        destinations: [
          'la-workspace'
        ]
        transformKql: 'source'
        outputStream: 'Microsoft-Event'
      }
      {
        streams: [
          'Microsoft-Perf'
        ]
        destinations: [
          'la-workspace'
        ]
        transformKql: 'source'
        outputStream: 'Microsoft-Perf'
      }
    ]
  }
}

resource dcrAssociation 'Microsoft.Insights/dataCollectionRuleAssociations@2023-03-11' = {
  name: '${dcrName}-association'
  scope: vm
  properties: {
    dataCollectionRuleId: dcr.id
    description: 'Windows security telemetry collection rule'
  }
  dependsOn: [
    amaExtension
  ]
}

output amaExtensionId string = amaExtension.id
output dcrId string = dcr.id
output dcrName string = dcr.name
output dcrAssociationId string = dcrAssociation.id
